/*

 KONIEC.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 11 x 3
   Tile set      : graph.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define cierpienieTekstWidth 11
#define cierpienieTekstHeight 3
#define cierpienieTekstBank 0

const unsigned char cierpienieTekst[] =
{
  0xA9,0xAF,0xAB,0xB7,0xB6,0xAF,0xAB,0xB4,0xAF,0xAB,
  0x94,0x94,0xB4,0xAF,0xAD,0xAA,0xBC,0x94,0xB8,0xAF,
  0xC0,0x94,0xB4,0xAF,0xAB,0x94,0xB1,0xB5,0xC2,0xA9,
  0xBD,0xBC,0xE6
};

/* End of KONIEC.C */
