/*

 NAPIS_OPCJE.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : D:\gry\gb\dev\turbo_wieszcz\TW_0_6\img\graph.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define napis_opcjeWidth 10
#define napis_opcjeHeight 3
#define napis_opcjeBank 0

const unsigned char napis_opcje[] =
{
  0x19,0x1A,0x1B,0x1C,0x1D,0x1E,0x1F,0x20,0x21,0x22,
  0x23,0x24,0x25,0x26,0x27,0x28,0x29,0x2A,0x2B,0x2C,
  0x2D,0x2E,0x2F,0x30,0x31,0x32,0x33,0x34,0x35,0x36
};


/* End of NAPIS_OPCJE.C */
