/*

 NAPIS_KONIEC3.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : D:\gry\gb\dev\turbo_wieszcz\TW_0_6\img\graph.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define napis_koniecPWidth 10
#define napis_koniecPHeight 3
#define napis_koniecPBank 0

const unsigned char napis_koniecP[] =
{
  0x37,0x38,0x5D,0x3A,0x5F,0x60,0x3A,0x63,0x3F,0x40,
  0x41,0x42,0x5E,0x44,0x61,0x62,0x47,0x64,0x49,0x4A,
  0x4B,0x4C,0x4D,0x4E,0x4F,0x50,0x51,0x52,0x53,0x54
};

/* End of NAPIS_KONIEC3.C */
