/*

 NAPIS_MENU.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 10 x 3
   Tile set      : D:\gry\gb\dev\turbo_wieszcz\TW_0_6\img\graph.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define napis_menuWidth 10
#define napis_menuHeight 3
#define napis_menuBank 0

const unsigned char napis_menu[] =
{
  0x00,0x01,0x02,0x03,0x00,0x00,0x00,0x00,0x04,0x05,
  0x06,0x07,0x08,0x09,0x0A,0x0B,0x0C,0x0D,0x0E,0x0F,
  0x10,0x00,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18
};

/* End of NAPIS_MENU.C */
