/*

 TYTUL.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 18 x 1
   Tile set      : D:\gry\gb\dev\turbo_wieszcz\img\graph.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define tytulWidth 18
#define tytulHeight 1
#define tytulBank 0

unsigned char tytul[] =
{
  0x94,0x94,0x94,0x94,0x94,0x94,0xB8,0xB6,0xB5,0xB1,
  0xC3,0xB0,0x94,0x94,0x94,0x94,0x94,0x94
};

/* End of TYTUL.C */
